### PR TITLE
[FEATURE BUGFIX] Added basic theming support and multiple bug fixes.

### PR DESCRIPTION
**Pull request by laaledesiempre**
List of problems solved in this pull request:
- [x] Basic theming support as planed at (#13)
- [x] Solved bug that made the chat block move away at the start because main tab was empty (#15)
- [x] Solved javascript beeing loaded before the DOM (#17)
- [x] Solved problems and lacks of styles at home screen (#14)

first, this is just part of the  planned changes for theming support. everything seems to work properly but now is time to get some feedback. the idea is allowing users to add and share multiple themes in the future. so there we go!

the chatblock bug was something that i dont know why didn't solved it time ago. just added a fixed height

we have discussed about javascript before/after DOM in (#17) so dont feel necesary to add it here

i made a rework of the whole homescreen on the first pull request but all that code was on `index-src.html` instead of `index.html` that is the one is hosted so, now i just copypasted that on the correct file, but can be buggy, please tell me if you need some changes. thats why the homescreen felt odd to me.

### CODE REVIEW

**Comment by Dpeta** [comment]
Threw an error for me on first launch:


Think if there isn't already a saved customTheme then customTheme.colors is set to null in loadSavedTheme, which throws an error in changeTheme. Maybe there could be a check for localstorage returning unusable values or a Theme getting invalid values or smthin.

**Comment by Dpeta** [comment]
Defer attribute for the script seems to work fine btw, I'd rather just use that instead of putting it at the end of body.

**Comment by laaledesiempre** [comment]
last commit should fix it, i was thinking on error handling while i was planning the feature but forgot to actually adding it.

**Comment by laaledesiempre** [comment]
> Defer attribute for the script seems to work fine btw, I'd rather just use that instead of putting it at the end of body.

if it works i'm okey with that 100%. can you plase make that change? having some trubles with pc now. thank u.

**Comment by Dpeta** [comment]
woo yeah woo yeah

**Comment by Dpeta** [comment]
> > Defer attribute for the script seems to work fine btw, I'd rather just use that instead of putting it at the end of body.
> 
> if it works i'm okey with that 100%. can you please make that change? having some trubles with pc now. thank u.

Yeah sure 👍

**Comment by Dpeta** [comment]
think this should be good to merge now?

**Pull request merged**
